# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    ruby: "3.3"
  jobs:
    pre_build:
      - gem install html-proofer -v ">= 5.0.9"  # Ensure version >= 5.0.9
    post_build:
      # Check everything except 403s, 400s, and a jneurosci, which returns 404 but the link works when clicking.
      # Skip files referencing to sklearn docs, which uses Text fragment URLs (#:~:text=)
      # that are not recognized as valid anchors by htmlproofer yet, see issue below
      # https://github.com/gjtorikian/html-proofer/issues/849
      - htmlproofer $READTHEDOCS_OUTPUT/html --checks Links,Scripts,Images --ignore-urls "https://fonts.gstatic.com,/scikit-learn\.org/,https://celltypes.brain-map.org/experiment/electrophysiology/478498617,https://www.jneurosci.org/content/25/47/11003,https://www.nature.com/articles/s41467-017-01908-3,https://doi.org/10.1038/s41467-017-01908-3,https://www.taylorfrancis.com/books/mono/10.4324/9780203774441/applied-multiple-regression-correlation-analysis-behavioral-sciences-jacob-cohen-patricia-cohen-stephen-west-leona-aiken" --assume-extension --check-external-hash --ignore-status-codes 400,403,302,0,503 --ignore-files "/.+\/_static\/.+/","/.+\/stubs\/.+/","/.+\/tutorials/plot_02_head_direction.+/","/.+\/how_to_guide\/plot_06_sklearn_pipeline_cv_demo.+/","/.+\/tutorials\/plot_03_grid_cells.+/","/.+\/tutorials\/plot_06_calcium_imaging.+/"
      # therefore for this file I am not checking the figures.
      - htmlproofer $READTHEDOCS_OUTPUT/html/tutorials/plot_02_head_direction.html  --checks Links,Scripts --ignore-urls "https://www.jneurosci.org/content/25/47/11003" --ignore-status-codes 400
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs

formats:
  - pdf
  - htmlzip
