import datetime
import tempfile
from pathlib import Path

import jax
import numpy as np
import pynapple as nap
from pynwb import NWBHDF5IO, NWBFile, TimeSeries
from pynwb.misc import Units

import nemos as nmo

nap.nap_config.suppress_conversion_warnings = True

N_NEURONS = 10
T = 50  # seconds
BIN_SIZE = 0.005  # seconds
WINDOW_SIZE_S = 0.2  # convolution window, seconds
RNG = np.random.default_rng(123)
DEFAULT_NWB_FOLDER = Path(tempfile.gettempdir())
DEFAULT_NWB_FILENAME = "stochastic_optim_toy_data.nwb"
DEFAULT_NWB_PATH = DEFAULT_NWB_FOLDER / DEFAULT_NWB_FILENAME


def _build_banded_coupling() -> np.ndarray:
    """Refractory/inhibitory coupling: strong self, decaying with neuron distance."""
    self_filter = np.array([-3.0, -2.0, -1.0, -0.4, -0.1])
    neighbor_filter = np.array([-2.0, -1.3, -0.6, -0.2, 0.0])
    lam, max_dist = 1.5, 4  # band width / reach in neurons
    coupling = np.zeros((N_NEURONS, N_NEURONS, 5))
    for i in range(N_NEURONS):
        for j in range(N_NEURONS):
            d = abs(i - j)
            if d == 0:
                coupling[i, j] = self_filter
            elif d <= max_dist:
                coupling[i, j] = np.exp(-((d / lam) ** 2)) * neighbor_filter
    return coupling


def _simulate_batching_data() -> tuple[nap.TsGroup, nap.TsdFrame, nap.TsdFrame]:
    window_size = int(WINDOW_SIZE_S / BIN_SIZE)
    n_bins = int(T / BIN_SIZE)
    basis = nmo.basis.RaisedCosineLogConv(5, window_size=window_size)
    # same kernels the features are built from -> simulation and fit stay consistent
    coupling_basis = nmo.basis.RaisedCosineLogEval(5).evaluate_on_grid(window_size)[1]

    spikes, _ = nmo.simulation.simulate_recurrent(
        coupling_coef=_build_banded_coupling(),
        feedforward_coef=np.zeros((N_NEURONS, 1)),
        intercepts=1.5 * np.ones(N_NEURONS),  # sets baseline rate (~30 Hz)
        random_key=jax.random.key(123),
        feedforward_input=np.zeros(
            (n_bins, N_NEURONS, 1)
        ),  # rate is pure spike history
        coupling_basis_matrix=coupling_basis,
        init_y=np.zeros((window_size, N_NEURONS)),
        inverse_link_function=jax.numpy.exp,  # match the Poisson GLM link
    )
    spikes = np.asarray(spikes).astype(int)

    # expand binned counts into jittered spike times, then round-trip as before
    t_idx, n_idx = np.nonzero(spikes)
    reps = spikes[t_idx, n_idx]
    t_idx, n_idx = np.repeat(t_idx, reps), np.repeat(n_idx, reps)
    spike_times_s = t_idx * BIN_SIZE
    sort_idx = np.argsort(spike_times_s)

    units = nap.Tsd(spike_times_s[sort_idx], n_idx[sort_idx]).to_tsgroup()
    spike_trains = units.count(BIN_SIZE, ep=nap.IntervalSet(0, T))
    X = basis.compute_features(spike_trains)
    return units, spike_trains, X


def _write_to_nwb(
    units: nap.TsGroup,
    spike_trains: nap.TsdFrame,
    X: nap.TsdFrame,
    nwb_path: Path | None = None,
) -> Path:
    """
    Write the generated data to an NWB file.

    Params
    ------
    units :
        Spike times in a pynapple TsGroup.
    spike_trains :
        Binned spike counts.
    X :
        Computed features.
    nwb_path :
        Path where the NWB file should be saved.
        If None (default), it's saved in a temporary folder.

    Returns
    -------
    nwb_path :
        Path of the saved NWB file.
    """
    # create an empty NWB file
    nwbfile = NWBFile(
        session_description="Toy data for stochastic optimization documentation.",
        identifier="stochastic_optim_doc",
        session_start_time=datetime.datetime.now(datetime.timezone.utc),
    )

    # create the units table with a descriptive description, rather than
    # letting add_unit() autogenerate one ("Autogenerated by NWBFile")
    nwbfile.units = Units(
        name="units",
        description="Spike times of the simulated neurons.",
    )

    # add spike times of each unit
    for unit in units.values():
        nwbfile.add_unit(spike_times=unit.t)

    # add the binned spike counts and the computed features X so that they
    # don't have to be computed again
    processing_module = nwbfile.create_processing_module(
        name="derived_features",
        description="Features constructed from the toy data",
    )
    processing_module.add(
        TimeSeries(
            name="spike_trains",
            data=spike_trains.values,
            unit="count",
            description=f"Spike counts binned at {BIN_SIZE * 1000:.0f} ms.",
            timestamps=spike_trains.t,
        )
    )
    processing_module.add(
        TimeSeries(
            name="X",
            data=X.values,
            unit="a.u.",
            description="Spike trains convolved with a 5D RaisedCosineLogConv basis."
            f"{WINDOW_SIZE_S * 1000:.0f} ms window size.",
            timestamps=X.t,
        )
    )

    # write NWB file to disk
    # note: using as a context manager doesn't seem to close the file
    if nwb_path is None:
        nwb_path = DEFAULT_NWB_PATH

    io = NWBHDF5IO(nwb_path, "w")
    io.write(nwbfile)
    io.close()

    return nwb_path


def _simulate_and_write_to_disk(nwb_path: Path | None = None) -> Path:
    """
    Simulate data and write to disk.

    Shorthand for calling _simulate_batching_data, then _write_to_nwb.
    """
    return _write_to_nwb(*_simulate_batching_data(), nwb_path=nwb_path)
