import datetime
import tempfile
from pathlib import Path

import numpy as np
import pynapple as nap
from pynwb import NWBHDF5IO, NWBFile, TimeSeries
from pynwb.misc import Units

import nemos as nmo

nap.nap_config.suppress_conversion_warnings = True

N_NEURONS = 10
T = 50  # seconds
BIN_SIZE = 0.005  # seconds
WINDOW_SIZE_S = 0.2  # convolution window, seconds
RNG = np.random.default_rng(123)
DEFAULT_NWB_FOLDER = Path(tempfile.gettempdir())
DEFAULT_NWB_FILENAME = "stochastic_optim_toy_data.nwb"
DEFAULT_NWB_PATH = DEFAULT_NWB_FOLDER / DEFAULT_NWB_FILENAME


def _simulate_batching_data() -> tuple[nap.TsGroup, nap.TsdFrame, nap.TsdFrame]:
    basis = nmo.basis.RaisedCosineLogConv(5, window_size=int(WINDOW_SIZE_S / BIN_SIZE))

    time_axis = np.linspace(0, T, 5000).reshape(-1, 1)
    rate = np.exp(
        np.sin(time_axis + np.linspace(0, np.pi * 2, N_NEURONS).reshape(1, N_NEURONS))
    )
    spike_t, spike_id = np.where(RNG.poisson(rate))
    spike_times_s = spike_t / len(time_axis) * T

    units = nap.Tsd(spike_times_s, spike_id).to_tsgroup()
    spike_trains = units.count(BIN_SIZE)

    X = basis.compute_features(spike_trains)

    return units, spike_trains, X


def _write_to_nwb(
    units: nap.TsGroup,
    spike_trains: nap.TsdFrame,
    X: nap.TsdFrame,
    nwb_path: Path | None = None,
) -> Path:
    """
    Write the generated data to an NWB file.

    Params
    ------
    units :
        Spike times in a pynapple TsGroup.
    spike_trains :
        Binned spike counts.
    X :
        Computed features.
    nwb_path :
        Path where the NWB file should be saved.
        If None (default), it's saved in a temporary folder.

    Returns
    -------
    nwb_path :
        Path of the saved NWB file.
    """
    # create an empty NWB file
    nwbfile = NWBFile(
        session_description="Toy data for stochastic optimization documentation.",
        identifier="stochastic_optim_doc",
        session_start_time=datetime.datetime.now(datetime.timezone.utc),
    )

    # create the units table with a descriptive description, rather than
    # letting add_unit() autogenerate one ("Autogenerated by NWBFile")
    nwbfile.units = Units(
        name="units",
        description="Spike times of the simulated neurons.",
    )

    # add spike times of each unit
    for unit in units.values():
        nwbfile.add_unit(spike_times=unit.t)

    # add the binned spike counts and the computed features X so that they
    # don't have to be computed again
    processing_module = nwbfile.create_processing_module(
        name="derived_features",
        description="Features constructed from the toy data",
    )
    processing_module.add(
        TimeSeries(
            name="spike_trains",
            data=spike_trains.values,
            unit="count",
            description=f"Spike counts binned at {BIN_SIZE * 1000:.0f} ms.",
            timestamps=spike_trains.t,
        )
    )
    processing_module.add(
        TimeSeries(
            name="X",
            data=X.values,
            unit="a.u.",
            description="Spike trains convolved with a 5D RaisedCosineLogConv basis."
            f"{WINDOW_SIZE_S * 1000:.0f} ms window size.",
            timestamps=X.t,
        )
    )

    # write NWB file to disk
    # note: using as a context manager doesn't seem to close the file
    if nwb_path is None:
        nwb_path = DEFAULT_NWB_PATH

    io = NWBHDF5IO(nwb_path, "w")
    io.write(nwbfile)
    io.close()

    return nwb_path


def _simulate_and_write_to_disk(nwb_path: Path | None = None) -> Path:
    """
    Simulate data and write to disk.

    Shorthand for calling _simulate_batching_data, then _write_to_nwb.
    """
    return _write_to_nwb(*_simulate_batching_data(), nwb_path=nwb_path)
